version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5436:5432'
    environment:
      POSTGRES_DB: gardenia_plant_species
      POSTGRES_USER: gardenia
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U gardenia -d gardenia_plant_species']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
